name: CMake wxWidgets Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  WX_VERSION: 3.2  # Versión de wxWidgets a instalar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install wxWidgets dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            libwxgtk${WX_VERSION}-dev \
            libgtk-3-dev \
            make \
            g++ \
            cmake \
            libgl1-mesa-dev \
            libglu1-mesa-dev

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DwxWidgets_CONFIG_OPTIONS="--prefix=/usr"  # Asegura la detección correcta

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j $(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
